### ISSUE TITLE
Request to implement GetDestinyEntityDefinition

### ISSUE THREAD

**Issue by Tzelon** [alexanderwe/the-traveler#23]
First, thank you for the package it's very helpful.
How can I help with implementing GetDestinyEntityDefinition request?

**Comment by alexanderwe** [comment]
Generally the process would be to make a pull request to the repository with your changes and I will look at the changes and if they are alright I merge the change into the repository. 

What exactly do you want to add to the request, because it is already implement ?

**Comment by Tzelon** [comment]
I want to implement this API
https://bungie-net.github.io/multi/operation_get_Destiny2-GetDestinyEntityDefinition.html#operation_get_Destiny2-GetDestinyEntityDefinition

I can't find it right now.

**Comment by alexanderwe** [comment]
I think you are looking for this: https://github.com/alexanderwe/the-traveler/blob/feb9125/src/Traveler.ts#L106 
Am I correct ?

**Comment by Tzelon** [comment]
Yes! thank you.
exactly what I was looking for. 

Missed it because I was looking at the main Github page :|

**Comment by alexanderwe** [comment]
You're welcome ! 
But in fact you are right, the method is missing on the README file. I will add it.

**Comment by alexanderwe** [comment]
Fixed in https://github.com/alexanderwe/the-traveler/commit/b30943fa448fff14e68688c5396e5fb8d4ce8ddc
