### ISSUE TITLE
IDestinyCharacterComponent#emblemBackgroundPath is misspelled

### ISSUE THREAD

**Issue by rehret** [alexanderwe/the-traveler#33]
# Bug Report
## Your Environment
| Software            | Version(s) |
| ---------------- | ---------- |
| the-traveler       | 0.7.2        |
| Node                 | 8.9.0        |
| Operating System | Windows 10 |

## Expected Behavior
The property `emblemBackgroundPath` of `IDestinyCharacterComponent` should be spelled correctly.

## Current Behavior
The property `emblemBackgroundPath` is currently spelled `emplemBackgroundPath`.

## Code Sample
N/A

**Comment by alexanderwe** [comment]
@rehret Thanks for pointing out the spelling mistake. I will release a fix for it in the next minor release.

**Comment by rehret** [comment]
@alexanderwe Thanks!

**Comment by alexanderwe** [comment]
@rehret The issue is fixed with the new release https://github.com/alexanderwe/the-traveler/releases/tag/v0.7.3.
See also https://github.com/alexanderwe/the-traveler/blob/master/src/interfaces.ts#L178
