### ISSUE TITLE
es6-promise is listed as a dev-dependency but should be a regular dependency

### ISSUE THREAD

**Issue by xxbiohazrdxx** [alexanderwe/the-traveler#35]
Attempting to use the-traveler without es6-promise results in 

'Error: Cannot find module 'es6-promise'
Call stack places the error at HttpService.js:3:1 and from looking at HttpService.ts there's an import for 'es6-promise'

I'm not entirely familiar with your project so I can't tell if the package.json should be updated so that it is no longer listed as a devdependency or if it is being included unnecessarily.

**Comment by alexanderwe** [comment]
@xxbiohazrdxx Thanks for submitting this issue. You are right, I was importing the `es6-promise` unnecessarily in the `HttpService.js` file. I will remove the import and integrate the solution in the next release.

**Comment by xxbiohazrdxx** [comment]
Yep. I’ll check tomorrow and let you know

**Comment by alexanderwe** [comment]
Perfect, thanks for checking !
