### ISSUE TITLE
Some enums updated

### ISSUE THREAD

**Issue by vpzed** [alexanderwe/the-traveler#4]
Some of the enums have updated with the new release of the OpenAPI spec files.

For example the [ActivityModeType](https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType.html#schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType) now includes Raid and TrialsOfTheNine; however, these updates are not reflected in enums.ts.

**Comment by alexanderwe** [comment]
I updated the `ActivityModeType` as well as checked for other changes of the enums which are currently used.
