### ISSUE TITLE
Manifest is not a function

### ISSUE THREAD

**Issue by Native-Coder** [alexanderwe/the-traveler#40]
# Bug Report
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| the-traveler      | 0.7.4
| Node            | 8.9.1
| Operating System | Ubuntu Server 16.04 LTS

## Expected Behavior
Creating an instance of `manifest` using the path to the manifest.content file should create an sqlite3 database handle to the manifest database as specified in the documentation

## Current Behavior
Process fails with the error
`(node:31520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Manifest is not a constructor
`

## Code Sample
```
const Manifest = require( 'the-traveler/build/Manifest' );
const manifest = new Manifest( __dirname + '/../destiny-2/manifest.content' );
const queryResult = await manifest.queryManifest( 'SELECT name FROM sqlite_master WHERE type="table"' );
		
console.log( queryResult );
```

## Other Notes
due to issue #39 I manually  unzipped the manifest, renamed it manifest.content, and placed it in the appropriate directory.

**Comment by Native-Coder** [comment]
this issue persists after the closing of issue #39

**Comment by Native-Coder** [comment]
I found the root of the issue. the documentation states

`import Manifest from 'the-traveler/build/Manifest'` which I couldn't get to work. So I used

`const Manifest = require( 'the-traveler/build/Manifest' );`

Looking at the source code I see that what I needed was `const Manifest=require( 'the-traveler/build/Manifest' ).default`

Are you able to use import statements with node 8? From what I'm reading we are still using require unless you specify the flag `--experimental-modules`

**Comment by alexanderwe** [comment]
Right now, import statements are not supported in node 8 as far as I know. So you would need to stick to `const Manifest = require( 'the-traveler/build/Manifest' ).default` to use the Manifest class in node 8, and generally using the `require` keyword in node 8.

**Comment by alexanderwe** [comment]
I will close this issue for now. If you still have questions feel free to ask
