### ISSUE TITLE
Public Vendors Endpoint

### ISSUE THREAD

**Issue by Jakosaur** [alexanderwe/the-traveler#43]
Could GetPublicVendors Endpoint be added sometime in the future? 👍 

I think this is the new endpoint for the public Xur API!

https://github.com/Bungie-net/api/issues/502

https://bungie-net.github.io/multi/operation_get_Destiny2-GetPublicVendors.html#operation_get_Destiny2-GetPublicVendors

**Comment by Jakosaur** [comment]
NP, can't wait. Thanks again 🙂

**Comment by alexanderwe** [comment]
@Jakosaur Sorry for long time now answer... there was a lot of stuff going on in the last months. I will update the library and include endpoints.

**Comment by Jakosaur** [comment]
No problem! Thanks 🙂

**Comment by alexanderwe** [comment]
@Jakosaur I released a new version which includes the endpoint. It is available via npm or as a download here: https://github.com/alexanderwe/the-traveler/releases/tag/v1.0.1 

If you find some errors, please file an issue and I will look at it :)
