### ISSUE TITLE
Importing enums?

### ISSUE THREAD

**Issue by pv2b** [alexanderwe/the-traveler#44]
The docs say:

> If you want to use this package inside a ES5 project you can import it like so:

```
var Traveler = require('the-traveler').default;
const Enums = require('the-traveler/build/enums')

const traveler = new Traveler({
    apikey: 'yourAPIkey',
    userAgent: 'yourUserAgent' //used to identify your request to the API
});

//Access the enums (example componentType profiles)
var profilesType = Enums.ComponentType.Profiles;

```

But at least when I npm install the-traveler, my node_modules/the-traveler/build directory does not contains any "enums".

**Comment by alexanderwe** [comment]
You are right, I forgot do update the docs accordingly, sorry for the inconvenience. The enumerations can be imported from `the-traveler/type-definitions/destiny2` and `the-traveler/type-definitions/additions`. I will update the documentation to mitigate this issue.

**Comment by alexanderwe** [comment]
Updated the README and the documentation to reflect the new location of enums.
